---
- name: Set GOPATH
  lineinfile:
    dest: "{{ ansible_user_dir }}/.bashrc"
    regexp: '^export GOPATH='
    line: 'export GOPATH=$HOME/go'

- name: Set PATH
  lineinfile:
    dest: "{{ ansible_user_dir }}/.bashrc"
    regexp: '^export PATH='
    line: 'export PATH="$PATH:${GOPATH//://bin:}/bin:$HOME/go/src/github.com/openshift/origin/_output/local/bin/linux/amd64:$HOME/go/src/github.com/openshift/source-to-image/_output/local/bin/linux/amd64"'

- name: Set CDPATH
  lineinfile:
    dest: "{{ ansible_user_dir }}/.bashrc"
    regexp: '^export CDPATH='
    line: 'export CDPATH=.:${GOPATH//://src:}/src:$HOME/go/src/github.com/openshift:$HOME/go/src/github.com/rhcarvalho'
