---
- name: Bootstrap dependencies of Ansible modules
  become: yes
  raw: dnf install -y python2-dnf libselinux-python
  register: dnf_result
  changed_when: '"Nothing to do." not in dnf_result.stdout_lines'

- include: docker-pre.yml
  when: '"docker" in "{{ pkgs }}"'

- name: Install system packages
  become: yes
  package: name={{ item }} state=latest
  with_items: "{{ pkgs }}"

- include: docker-post.yml
  when: '"docker" in "{{ pkgs }}"'

- name: Install pip packages
  become: yes
  pip: name={{ item }} state=latest
  with_items: "{{ pip_pkgs }}"

- name: Set GOPATH
  lineinfile:
    dest: "{{ ansible_user_dir }}/.bashrc"
    regexp: '^export GOPATH='
    line: 'export GOPATH=$HOME/go'

- name: Set PATH
  lineinfile:
    dest: "{{ ansible_user_dir }}/.bashrc"
    regexp: '^export PATH='
    line: 'export PATH="$PATH:${GOPATH//://bin:}/bin"'

- name: Set CDPATH
  lineinfile:
    dest: "{{ ansible_user_dir }}/.bashrc"
    regexp: '^export CDPATH='
    line: 'export CDPATH=.:${GOPATH//://src:}/src:$HOME/go/src/github.com/openshift:$HOME/go/src/github.com/rhcarvalho'
